apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat3
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 2
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
    spec:
      containers:
      - image: rajiv4671/masterapp  
        name: tomcatapp
